### ISSUE TITLE
Relion 3 Beta - Install Error

### ISSUE THREAD

**Issue by JusticeForMikeBrown** [3dem/relion#380]
Hi

I am getting an issue with compiling Relion 3 Beta with Cuda on P100s.

gcc 6.3.0
3.12.0
cuda 9.2.88
openmpi 3.1.1

cmake arguments used:

```
==> Executing phase: 'cmake'
==> 'cmake' '/pbtech_mounts/homes027/user/prepos/spack/var/spack/stage/relion-3.0_beta-fpw2ruts4pdjjwipu2tst5ynvesin525/relion-3.0_beta' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:PATH=/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/relion-3.0_beta-fpw2ruts4pdjjwipu2tst5ynvesin525' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=FALSE' '-DCMAKE_INSTALL_RPATH:STRING=/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/relion-3.0_beta-fpw2ruts4pdjjwipu2tst5ynvesin525/lib;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/relion-3.0_beta-fpw2ruts4pdjjwipu2tst5ynvesin525/lib64;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/fftw-3.3.8-el7xq2sohhy6xp5skpcfehq52xka2xra/lib;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/openmpi-3.1.1-6zlw7u7cinxxt4ufu7w6osyzfukpighu/lib;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/hwloc-1.11.9-cbau5scpzb7mhug5254xmsatijbf2dxd/lib;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/libpciaccess-0.13.5-od6rgarvghypyg7fnnfjsv2p33oytjhc/lib;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/libxml2-2.9.8-bu63biyualkkyse3kiojsyjjjrabqc3w/lib;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/xz-5.2.4-nhtvde2in6md7tigknxqtltrlw2sjvt6/lib;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/zlib-1.2.11-3m5jwvclvb6tkffyfoijjpx3f6sizmyj/lib;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/numactl-2.0.11-2gduk6rrpencxeyhnmppv77cy6vdczm7/lib;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/fltk-1.3.3-24rmak4aa7wzb7fh2yqloji6k3kz5ukm/lib;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/libx11-1.6.5-ilxiqd6piijpel7dt72zkjudq6xollmy/lib;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/kbproto-1.0.7-54t6diklmslkvk5r6crtebarbu4fkg4p/lib;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/libxcb-1.13-kv5hcdzogk4mcyxkmx5pddmgqhgfpa7u/lib;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/libpthread-stubs-0.4-lqmtyjyi7tzcqcmked7tu77ga2btqrig/lib;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/libxau-1.0.8-5ugswfvnaujwtshjcbfwrm6evmm5mcv4/lib;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/xproto-7.0.31-xylfiyjwajogn3oblyyi6zj676b7g2mj/lib;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/libxdmcp-1.1.2-kbpq7nt3acts6bxryqe6z6el4byjfxs7/lib;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/xextproto-7.3.0-veoruuunuxwh7of4n35lno37ipux67dr/lib;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/libtiff-4.0.9-lg556vrhrmgfyzwhldshdqebdswpzxy6/lib;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/cuda-9.2.88-mpqngzkq65xifyfforlhfkkxp5cs7klv/lib64;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/libjpeg-turbo-1.5.90-egnmgjklvuo32x56x3bkr7gbhhsxnb3o/lib64' '-DCMAKE_PREFIX_PATH:STRING=/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/libtiff-4.0.9-lg556vrhrmgfyzwhldshdqebdswpzxy6;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/cmake-3.12.0-d6i3ujxpf5m4aiggveyzridh7rxbb6bh;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/fltk-1.3.3-24rmak4aa7wzb7fh2yqloji6k3kz5ukm;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/fftw-3.3.8-el7xq2sohhy6xp5skpcfehq52xka2xra;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/openmpi-3.1.1-6zlw7u7cinxxt4ufu7w6osyzfukpighu;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/cuda-9.2.88-mpqngzkq65xifyfforlhfkkxp5cs7klv' '-DCMAKE_C_FLAGS=-g' '-DCMAKE_CXX_FLAGS=-g' '-DGUI=True' '-DDoublePrec_CPU=True' '-DCUDA=ON' '-DCudaTexture=ON' '-DCUDA_ARCH=60'
CMake Warning (dev) at /pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/cmake-3.12.0-d6i3ujxpf5m4aiggveyzridh7rxbb6bh/share/cmake-3.12/Modules/CMakeDetermineCompilerId.cmake:56 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "CUDA" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  /pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/cmake-3.12.0-d6i3ujxpf5m4aiggveyzridh7rxbb6bh/share/cmake-3.12/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:7 (project)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /pbtech_mounts/homes027/user/prepos/spack/lib/spack/env/gcc/gcc
-- Check for working C compiler: /pbtech_mounts/homes027/user/prepos/spack/lib/spack/env/gcc/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
```

The `make install` errors:

```
make[2]: Leaving directory `/tmp/user/spack-stage/spack-stage-1flJMJ/relion-3.0_beta/spack-build'
make[2]: Leaving directory `/tmp/user/spack-stage/spack-stage-1flJMJ/relion-3.0_beta/spack-build'
[100%] Built target maingui
[100%] Built target pipeliner
make[1]: Leaving directory `/tmp/user/spack-stage/spack-stage-1flJMJ/relion-3.0_beta/spack-build'
/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/cmake-3.12.0-d6i3ujxpf5m4aiggveyzridh7rxbb6bh/bin/cmake -E cmake_progress_start /tmp/user/spack-stage/spack-stage-1flJMJ/relion-3.0_beta/spack-build/CMakeFiles 0
==> Executing phase: 'install'
==> 'make' '-j56' 'install'
/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/cmake-3.12.0-d6i3ujxpf5m4aiggveyzridh7rxbb6bh/bin/cmake -H/pbtech_mounts/homes027/user/prepos/spack/var/spack/stage/relion-3.0_beta-fpw2ruts4pdjjwipu2tst5ynvesin525/relion-3.0_beta -B/tmp/user/spack-stage/spack-stage-1flJMJ/relion-3.0_beta/spack-build --check-build-system CMakeFiles/Makefile.cmake 0
-- BUILD TYPE set to 'RelWithDebInfo'
-- Using provided CUDA_ARCH=60
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- CMAKE_C_COMPILER : /pbtech_mounts/homes027/user/prepos/spack/lib/spack/env/gcc/gcc
-- CMAKE_CXX_COMPILER : /pbtech_mounts/homes027/user/prepos/spack/lib/spack/env/gcc/g++
-- MPI_C_COMPILER : /pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/openmpi-3.1.1-6zlw7u7cinxxt4ufu7w6osyzfukpighu/bin/mpicc
-- MPI_CXX_COMPILER : /pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/openmpi-3.1.1-6zlw7u7cinxxt4ufu7w6osyzfukpighu/bin/mpicxx
-- CMAKE_CXX_COMPILER_ID : GNU
-- Found MPI_C: /pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/openmpi-3.1.1-6zlw7u7cinxxt4ufu7w6osyzfukpighu/bin/mpicc (found version "3.1") 
-- Found MPI_CXX: /pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/openmpi-3.1.1-6zlw7u7cinxxt4ufu7w6osyzfukpighu/bin/mpicxx (found version "3.1") 
CMake Error at CMakeLists.txt:244 (include_directories):
  include_directories given empty-string as include directory.


-- MPI_INCLUDE_PATH :
-- MPI_LIBRARIES : /pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/openmpi-3.1.1-6zlw7u7cinxxt4ufu7w6osyzfukpighu/lib/libmpi_cxx.so;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/openmpi-3.1.1-6zlw7u7cinxxt4ufu7w6osyzfukpighu/lib/libmpi.so
-- MPI_CXX_INCLUDE_PATH :
-- MPI_CXX_LIBRARIES : /pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/openmpi-3.1.1-6zlw7u7cinxxt4ufu7w6osyzfukpighu/lib/libmpi_cxx.so;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/openmpi-3.1.1-6zlw7u7cinxxt4ufu7w6osyzfukpighu/lib/libmpi.so
-- X11 and FLTK were found
-- FLTK_LIBRARIES: /pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/fltk-1.3.3-24rmak4aa7wzb7fh2yqloji6k3kz5ukm/lib/libfltk_images.so;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/fltk-1.3.3-24rmak4aa7wzb7fh2yqloji6k3kz5ukm/lib/libfltk_forms.so;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/fltk-1.3.3-24rmak4aa7wzb7fh2yqloji6k3kz5ukm/lib/libfltk.so;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/libx11-1.6.5-ilxiqd6piijpel7dt72zkjudq6xollmy/lib/libX11.so;/usr/lib64/libXext.so;/usr/lib64/libm.so
-- Found FFTW
-- FFTW_PATH: /pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/fftw-3.3.8-el7xq2sohhy6xp5skpcfehq52xka2xra/include
-- FFTW_INCLUDES: /pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/fftw-3.3.8-el7xq2sohhy6xp5skpcfehq52xka2xra/include
-- FFTW_LIBRARIES: /pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/fftw-3.3.8-el7xq2sohhy6xp5skpcfehq52xka2xra/lib/libfftw3f.so;/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/fftw-3.3.8-el7xq2sohhy6xp5skpcfehq52xka2xra/lib/libfftw3.so
BUILD_SHARED_LIBS = OFF
-- Building static libs (larger build size and binaries)
Running apps/CMakeLists.txt...
-- CMAKE_BINARY_DIR:/tmp/user/spack-stage/spack-stage-1flJMJ/relion-3.0_beta/spack-build
TIFF FOUND
-- Found OpenMP_C: -fopenmp
-- Found OpenMP_CXX: -fopenmp
-- Found OpenMP: TRUE
OPENMP FOUND
-- Configuring incomplete, errors occurred!
See also "/tmp/user/spack-stage/spack-stage-1flJMJ/relion-3.0_beta/spack-build/CMakeFiles/CMakeOutput.log".
See also "/tmp/user/spack-stage/spack-stage-1flJMJ/relion-3.0_beta/spack-build/CMakeFiles/CMakeError.log".
make: *** [cmake_check_build_system] Error 1
```
**/tmp/user/spack-stage/spack-stage-1flJMJ/relion-3.0_beta/spack-build/CMakeFiles/CMakeError.log**

```
Determining if the pthread_create exist failed with the following output:
Change Dir: /tmp/user/spack-stage/spack-stage-1flJMJ/relion-3.0_beta/spack-build/CMakeFiles/CMakeTmp

Run Build Command:"/bin/gmake" "cmTC_5311f/fast"
/bin/gmake -f CMakeFiles/cmTC_5311f.dir/build.make CMakeFiles/cmTC_5311f.dir/build
gmake[1]: Entering directory `/tmp/user/spack-stage/spack-stage-1flJMJ/relion-3.0_beta/spack-build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_5311f.dir/CheckSymbolExists.c.o
/pbtech_mounts/homes027/user/prepos/spack/lib/spack/env/gcc/gcc   -fPIC    -o CMakeFiles/cmTC_5311f.dir/CheckSymbolExists.c.o   -c /tmp/user/spack-stage/spack-stage-1flJMJ/relion-3.0_beta/spack-build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_5311f
/pbtech_mounts/homes027/user/prepos/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/cmake-3.12.0-d6i3ujxpf5m4aiggveyzridh7rxbb6bh/bin/cmake -E cmake_link_script CMakeFiles/cmTC_5311f.dir/link.txt --verbose=1
/pbtech_mounts/homes027/user/prepos/spack/lib/spack/env/gcc/gcc -fPIC     -rdynamic CMakeFiles/cmTC_5311f.dir/CheckSymbolExists.c.o  -o cmTC_5311f 
CMakeFiles/cmTC_5311f.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_5311f] Error 1
gmake[1]: Leaving directory `/tmp/user/spack-stage/spack-stage-1flJMJ/relion-3.0_beta/spack-build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_5311f/fast] Error 2

File /tmp/user/spack-stage/spack-stage-1flJMJ/relion-3.0_beta/spack-build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}
```

**Comment by biochem-fan** [comment]
Does it compile outside Spack?

**Comment by JusticeForMikeBrown** [comment]
Hi @biochem-fan 

I have no idea.  We use Spack to manage our software.

I cannot compile Relion 3 beta with or without Cuda.  Same error.

**Comment by JusticeForMikeBrown** [comment]
I was able to compile using cmake-3.9.4

**Comment by alburse** [comment]
Hi J. for Mike Brown

Would you elaborate more on how you were able to compile Relion3? I get Ld exit status error either on make or make install step. It is very frustrating. I tried cmake/3.8.1 and 3.11.1. I tried Cuda8 and Cuda9. I was able to compile it without the GUI support. It is confusing.

I used gcc as the compiler for GPU accelerated version.

**Comment by alburse** [comment]
I could finally compiled it on Sherlock at Stanford. There were couple of issues. The flavor of programs worked for me are the following
cmake/3.8.1 - worked (3.11.1 did not work)
manually pointing gcc to cmake did not work, I used default cc on Sherlock. 
cuda/9.2.148 - worked
precompiled FLTK did not work - FLTK compiled with Relion worked.
openmpi/2.0.2 worked - I did not try others

I tried combination of all of these
