### ISSUE TITLE
RELION (3.1/4/5) fails to build with CUDA 12.9 (workaround/fix)

### ISSUE THREAD

**Issue by rbs-sci** [3dem/relion#1273]
**Problem:** RELION (CUDA-12 patched 3.1, RELION 4 and RELION 5) all fail to build with CUDA 12.9 (RTX 5060Ti 16GB with driver 575.57) due to "missing" `nvToolsExt.h` (and others).

Build fails at `ml_optimiser.cpp.o` step.

**Cause:** nVidia removed several header files from `/usr/local/cuda/include` but left duplicates in the directory `nvtx3`.

**Environment:**
 - OS: Ubuntu 24.04 (Mint 22.1)
 - MPI runtime: OpenMPI (v3.1)
 - Compiler: GCC 12
 - RELION version: 3.1 (patched for CUDA-12 support), version 4 (last) and version 5 (latest commit as of 2025/06/25)
 - Memory: 128 GB
 - CPU: Ryzen 9700X
 - GPU: RTX 5060Ti
 - CUDA: 12.9

**Error:**

```
[ 11%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_optimiser.cpp.o
/home/username/relion_build/relion/src/ml_optimiser.cpp:48:10: fatal error: nvToolsExt.h: No such file or directory
   48 | #include <nvToolsExt.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/apps/CMakeFiles/relion_lib.dir/build.make:608: src/apps/CMakeFiles/relion_lib.dir/__/ml_optimiser.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:338: src/apps/CMakeFiles/relion_lib.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Workaround:**
A quick workaround is symlink all files/directories from `nvtx3` directory to `/usr/local/cuda/include`.

Full fix would require some adjustments to the cmake build files (likely in the FindCUDA section) or code to point at new location (which would break old CUDA). From some searching it seems like it's been deprecated (or is that FindCUDA?) but this is the first CUDA version I've had this error during compilation. Other systems running older CUDA (11.8, 12.6) have `nvToolsExt.h` and other header files in the right place (`/usr/local/cuda/include`).

**Comment by rbs-sci** [comment]
Thanks for the quick fix!
